//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDagNetWallet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XDagNetWallet.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Common_ConfirmTitle {
            get {
                return ResourceManager.GetString("Common_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Common_MessageTitle {
            get {
                return ResourceManager.GetString("Common_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting account....
        /// </summary>
        internal static string LogonWindow_ConnectingAccount {
            get {
                return ResourceManager.GetString("LogonWindow_ConnectingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Wallet.
        /// </summary>
        internal static string LogonWindow_ConnectWallet {
            get {
                return ResourceManager.GetString("LogonWindow_ConnectWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Failed:.
        /// </summary>
        internal static string LogonWindow_InitializeFailed {
            get {
                return ResourceManager.GetString("LogonWindow_InitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialzing Account....
        /// </summary>
        internal static string LogonWindow_InitializingAccount {
            get {
                return ResourceManager.GetString("LogonWindow_InitializingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaspsed Time: [{0}] (Usually needs about 10-15 minutes)....
        /// </summary>
        internal static string LogonWindow_InitializingElapsedTime {
            get {
                return ResourceManager.GetString("LogonWindow_InitializingElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Wallet.
        /// </summary>
        internal static string LogonWindow_RegisterWallet {
            get {
                return ResourceManager.GetString("LogonWindow_RegisterWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching connection....
        /// </summary>
        internal static string LogonWindow_SearchingConnection {
            get {
                return ResourceManager.GetString("LogonWindow_SearchingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to XDAG Wallet.
        /// </summary>
        internal static string LogonWindow_Title {
            get {
                return ResourceManager.GetString("LogonWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect.
        /// </summary>
        internal static string Message_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Message_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string PasswordWindow_Enter {
            get {
                return ResourceManager.GetString("PasswordWindow_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Password:.
        /// </summary>
        internal static string PasswordWindow_InputPassword {
            get {
                return ResourceManager.GetString("PasswordWindow_InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not matched with previous you enterred..
        /// </summary>
        internal static string PasswordWindow_PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordWindow_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Password:.
        /// </summary>
        internal static string PasswordWindow_RetypePassword {
            get {
                return ResourceManager.GetString("PasswordWindow_RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password:.
        /// </summary>
        internal static string PasswordWindow_SetPassword {
            get {
                return ResourceManager.GetString("PasswordWindow_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string SettingsWindow_ChooseLanguage {
            get {
                return ResourceManager.GetString("SettingsWindow_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Address format is incorrect..
        /// </summary>
        internal static string TransferWindow_AccountFormatError {
            get {
                return ResourceManager.GetString("TransferWindow_AccountFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To address:.
        /// </summary>
        internal static string TransferWindow_AddressTitle {
            get {
                return ResourceManager.GetString("TransferWindow_AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be a positive number..
        /// </summary>
        internal static string TransferWindow_AmountFormatError {
            get {
                return ResourceManager.GetString("TransferWindow_AmountFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Transaction Failed:.
        /// </summary>
        internal static string TransferWindow_CommitFailed {
            get {
                return ResourceManager.GetString("TransferWindow_CommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer has been committed. Please wait for a while to get it done..
        /// </summary>
        internal static string TransferWindow_CommitSuccess {
            get {
                return ResourceManager.GetString("TransferWindow_CommitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing transaction....
        /// </summary>
        internal static string TransferWindow_CommittingTransaction {
            get {
                return ResourceManager.GetString("TransferWindow_CommittingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to transfer {0} XDAGs to [{1}]?.
        /// </summary>
        internal static string TransferWindow_ConfirmTransfer {
            get {
                return ResourceManager.GetString("TransferWindow_ConfirmTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wallet balance is insufficient..
        /// </summary>
        internal static string TransferWindow_InsufficientAmount {
            get {
                return ResourceManager.GetString("TransferWindow_InsufficientAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer XDAG to address.
        /// </summary>
        internal static string TransferWindow_Title {
            get {
                return ResourceManager.GetString("TransferWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string TransferWindow_TransferTitle {
            get {
                return ResourceManager.GetString("TransferWindow_TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected and mining.
        /// </summary>
        internal static string WalletState_ConnectedAndMining {
            get {
                return ResourceManager.GetString("WalletState_ConnectedAndMining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to network.
        /// </summary>
        internal static string WalletState_ConnectedNetwork {
            get {
                return ResourceManager.GetString("WalletState_ConnectedNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to pool.
        /// </summary>
        internal static string WalletState_ConnectedPool {
            get {
                return ResourceManager.GetString("WalletState_ConnectedPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to network....
        /// </summary>
        internal static string WalletState_ConnectingNetwork {
            get {
                return ResourceManager.GetString("WalletState_ConnectingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to pool....
        /// </summary>
        internal static string WalletState_ConnectingPool {
            get {
                return ResourceManager.GetString("WalletState_ConnectingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string WalletState_Idle {
            get {
                return ResourceManager.GetString("WalletState_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading blocks....
        /// </summary>
        internal static string WalletState_LoadingBlocks {
            get {
                return ResourceManager.GetString("WalletState_LoadingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exists.
        /// </summary>
        internal static string WalletState_None {
            get {
                return ResourceManager.GetString("WalletState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering....
        /// </summary>
        internal static string WalletState_Registering {
            get {
                return ResourceManager.GetString("WalletState_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseting engine....
        /// </summary>
        internal static string WalletState_ResetingEngine {
            get {
                return ResourceManager.GetString("WalletState_ResetingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string WalletState_Stopped {
            get {
                return ResourceManager.GetString("WalletState_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized.
        /// </summary>
        internal static string WalletState_Synchronized {
            get {
                return ResourceManager.GetString("WalletState_Synchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        internal static string WalletState_Synchronizing {
            get {
                return ResourceManager.GetString("WalletState_Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer pending....
        /// </summary>
        internal static string WalletState_TransferPending {
            get {
                return ResourceManager.GetString("WalletState_TransferPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet address has been copied to Clipboard..
        /// </summary>
        internal static string WalletWindow_AddressCopied {
            get {
                return ResourceManager.GetString("WalletWindow_AddressCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string WalletWindow_AddressTitle {
            get {
                return ResourceManager.GetString("WalletWindow_AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        internal static string WalletWindow_BalanceTitle {
            get {
                return ResourceManager.GetString("WalletWindow_BalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string WalletWindow_StatusTitle {
            get {
                return ResourceManager.GetString("WalletWindow_StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string WalletWindow_TabAccount {
            get {
                return ResourceManager.GetString("WalletWindow_TabAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        internal static string WalletWindow_TabHistory {
            get {
                return ResourceManager.GetString("WalletWindow_TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string WalletWindow_TabTransfer {
            get {
                return ResourceManager.GetString("WalletWindow_TabTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDag Wallet.
        /// </summary>
        internal static string WalletWindow_Title {
            get {
                return ResourceManager.GetString("WalletWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Transaction.
        /// </summary>
        internal static string WalletWindow_TransferTitle {
            get {
                return ResourceManager.GetString("WalletWindow_TransferTitle", resourceCulture);
            }
        }
    }
}
